apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-metallb-config-k3s2
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/hook-dependency: system-metallb-operator
spec:
  destination:
    namespace: metallb
    server: https://api.k3s2.ujstor.dev:6443
  project: ops-cluster-bootstrap
  source:
    path: cluster/k3s2-win/helm/system/metallb-config
    repoURL: https://github.com/Ujstor/k3s-single-node-multi-cluster-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: metallb-config
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
