apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-wordpress-ds
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "16"
spec:
  destination:
    namespace: wordpress
    server: https://api.k3s1.ujstor.com
  project: app-cluster-bootstrap
  source:
    path: cluster/k3s1-app/helm/wordpress-ds
    repoURL: https://github.com/Ujstor/k3s-prod-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: wordpress-ds
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
