apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-minio-operator
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  destination:
    namespace: minio-operator
    server: https://api.k3s1.ujstor.com:6443
  project: ops-cluster-bootstrap
  source:
    path: cluster/k3s1-app/helm/system/minio-operator
    repoURL: https://github.com/Ujstor/k3s-single-node-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: minio-operator
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
