apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-cluster-issuer-k3s4
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/hook-dependency: system-cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://api.k3s4.ujstor.dev:6444
  project: ops-cluster-bootstrap
  source:
    path: cluster/k3s0-ops/helm/system/cluster-issuer
    repoURL: https://github.com/Ujstor/k3s-single-node-multi-cluster-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: cluster-issuer
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
